### ISSUE TITLE
Crash in plugin, when right-clicking a folder

### ISSUE THREAD

**Issue by meven** [insynchq/dolphin-insync-plugin#3]
We have a bunch of duplicated crashes for this plugin (https://bugs.kde.org/show_bug.cgi?id=465658)

```
New crash information added by DrKonqi

dolphin (21.12.2) using Qt 5.15.2

Related to [bug 439664](https://bugs.kde.org/show_bug.cgi?id=439664) (https://bugs.kde.org/show_bug.cgi?id=439664) but experiencing with Insync version 3.7.12.50395

-- Backtrace (Reduced):
#4  0x00007f1bac8e3114 in QVariant::toString() const () from /lib64/libQt5Core.so.5
#5  0x00007f1b7840334c in FileItemActionInsyncPlugin::getContextMenuActions(QString const&) () from /usr/lib64/qt5/plugins/fileitemactioninsyncplugin.so
#6  0x00007f1b784030da in FileItemActionInsyncPlugin::actions(KFileItemListProperties const&, QWidget*) () from /usr/lib64/qt5/plugins/fileitemactioninsyncplugin.so
#7  0x00007f1bae712bc8 in KFileItemActionsPrivate::addPluginActionsTo(QMenu*, QMenu*, QStringList const&) () from /lib64/libKF5KIOWidgets.so.5
#8  0x0000557415e42f62 in DolphinContextMenu::addAdditionalActions(KFileItemListProperties const&) ()
```

**Comment by felagund** [comment]
With Qt6, it is no longer crashing, but I fixed the underlying issue anyway with this commit: https://github.com/insynchq/dolphin-insync-plugin/pull/5/commits/b054f40c2c59970bb5ac89281af99faabedd3c62

Now I just hope this gets picked up b distributors and Insync.
